config/routes.rb
Rails.application.routes.draw do

  get '/search', to: 'searches#search_result'

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update]  do
    resource :relationships, only:[:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :notifications, only: [:index] do
    collection do 
      delete 'destroy_all'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord

  default_scope -> { order(created_at: :desc) }

  belongs_to :book, optional: true
  belongs_to :book_comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def destroy_all
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to request.referer
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end

  def notification_form(notification)
    @visitor = notification.visitor
    @comment = nil
    @visitor_comment = notification.book_comment_id

    case notification.action
      when "dm" then
       @chat = Chat.find_by(id: notification.chat_id)&.message
        tag.a(@visitor.name, href:user_path(@visitor), style:"font-weight: bold;")+"があなたに"+tag.a('メッセージ',href:chat_path(notification.visitor), style:"font-weight: bold;")+"を送りました"
      when "comment" then
        @comment = BookComment.find_by(id: @visitor_comment)&.comment
        tag.a(@visitor.name, href:user_path(@visitor), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:book_path(notification.book_id), style:"font-weight: bold;")+"にコメントしました"
    end
  end
end

app/views/notifications/_notifications.html.erb
<table class="table table-borderless">
  <% @notifications.each do |notification|%>
  <tr>
    <td style="text-align: right;"><%= link_to user_path(notification.visitor) do %>
          <%= image_tag notification.visitor.get_profile_image, size:'50x50' %>
        <% end %>
    </td>
    <td><p><%= notification_form(notification) %>
        <span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)}前)" %></span>
        </p>
    </td>
  </tr>
  <% end %>
</table>

app/views/notifications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h3 class="text-center">通知</h3>
    </div>
  </div>
  <div class="row">
    <div class="col col-md-8 offset-md-2">
    <%= link_to destroy_all_notifications_path, method: :delete do %>
      <i class="fas fa-trash" style="color: black;"></i>
      <h7 style="color: black;">全削除</h7>
    <% end %>
    <% if @notifications.exists? %>
    <div class="users_index">
      <%= render "notifications" %>
    </div>
    <% else %>
      <p>通知はありません</p>
    <% end %>
    </div>
  </div>
</div>